### PR TITLE
Adding hash length extension + basic lattice

### PR DESCRIPTION
**Pull request by istrangeloop**
Hello, I'm a cryptography student who saw your project and wondered if I could contribute to it with some code I have from playing CTF. I added:
- MD4 and SHA1 length extension
- a gaussian lattice reduction
- tests for everything

I think I made everything fit together well with the rest of your code. If there is an issue just let me know. I would also like to know if you would welcome more changes in the future, I have some unfinished ECC things here too (it's Sage code tho).

### CODE REVIEW

**Comment by unicornsasfuel** [comment]
Hi @istrangeloop ! Thank you for the contribution. I have one concern and one question about the submission, though.

My concern: It adds Numpy as a new dependency which is not pure Python. I would like this project to be easily embedded into other tools including those which use Jython (which can only handle pure Python) such as Burp Suite Extender.

My question is about the code. I was able to find some of the code in other projects by Googling around. Is this your work, or is it taken from a project with a license that does not require attribution (public domain, CC-NoAttribution)? I don't want to run into licensing issues should someone use this in their own project.

**Comment by istrangeloop** [comment]
Hi and thanks for the feedback! A jython extension for burp seems like a
good idea, I'll keep in mind that all the fancy math will have to be done
by hand then.

Sorry for not thinking ahead on the copyright, I don't contribute often so
I didn't even notice when I was adapting my code, I guess that is an
important thing to consider. I found the algorithms for the hashes on
github at the time, I searched for them again just now to check and one
does not have a license and the other one just requires the license to be
present.

It's better to forget the PR for now then, I'll fix this when I find time
again.

Em qua, 3 de mar de 2021 14:11, unicornsasfuel <notifications@github.com>
escreveu:

**Comment by unicornsasfuel** [comment]
Hi there! Looks like this addresses the concerns I had before. I see you are now using code from BenWiederhake, and while I see that he commonly puts things in the public domain, I don't see a license attached to that particular bit of code.

**Comment by istrangeloop** [comment]
I sent him an email, I intended to open another PR when he answered, but I guess github automatically submitted my changes here and not only in the forked repo in my account, didn't know it did that...

**Comment by istrangeloop** [comment]
Ben said it was ok to use his hashes :D

**Comment by istrangeloop** [comment]
I think it's fine now, I did what he sugested.

**Comment by unicornsasfuel** [comment]
Thanks again for your work!

**Pull request merged**
